// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eONLSG1KHgwMrhOwnHxoKc3l584KoKA',
    appId: '1:38822547498:web:d0a3cd98887f5313637353',
    messagingSenderId: '38822547498',
    projectId: 'expenxo-ca8b4',
    authDomain: 'expenxo-ca8b4.firebaseapp.com',
    storageBucket: 'expenxo-ca8b4.firebasestorage.app',
    measurementId: 'G-5753WF6ZEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBkrQgrJGRRkxCkwA0pUmIvZ2AtMy3uE',
    appId: '1:38822547498:android:a7c57687a4ef60e2637353',
    messagingSenderId: '38822547498',
    projectId: 'expenxo-ca8b4',
    storageBucket: 'expenxo-ca8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRh-_g27KVl_gEC7fe5aDdMKSaBDrUj-8',
    appId: '1:38822547498:ios:76881f4ff69b01c0637353',
    messagingSenderId: '38822547498',
    projectId: 'expenxo-ca8b4',
    storageBucket: 'expenxo-ca8b4.firebasestorage.app',
    iosBundleId: 'com.example.expenxo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRh-_g27KVl_gEC7fe5aDdMKSaBDrUj-8',
    appId: '1:38822547498:ios:76881f4ff69b01c0637353',
    messagingSenderId: '38822547498',
    projectId: 'expenxo-ca8b4',
    storageBucket: 'expenxo-ca8b4.firebasestorage.app',
    iosBundleId: 'com.example.expenxo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1eONLSG1KHgwMrhOwnHxoKc3l584KoKA',
    appId: '1:38822547498:web:3edf098585db8d1f637353',
    messagingSenderId: '38822547498',
    projectId: 'expenxo-ca8b4',
    authDomain: 'expenxo-ca8b4.firebaseapp.com',
    storageBucket: 'expenxo-ca8b4.firebasestorage.app',
    measurementId: 'G-4Q1LNTYQX4',
  );
}
