import 'package:expenxo/models/category_model.dart';
import 'package:expenxo/models/transaction_model.dart';
import 'package:expenxo/services/auth_service.dart';
import 'package:expenxo/services/firestore_service.dart';
import 'package:expenxo/utils/constands/colors.dart';
import 'package:expenxo/utils/ui/ui_helper.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:expenxo/providers/preferences_provider.dart';
import 'package:expenxo/utils/toast_util.dart';
import 'package:provider/provider.dart';

class AddExpensePage extends StatefulWidget {
  const AddExpensePage({super.key});

  @override
  State<AddExpensePage> createState() => _AddExpensePageState();
}

class _AddExpensePageState extends State<AddExpensePage> {
  // Dropdown initial values
  String selectedCategory = 'Food & Dining';
  String selectedPayment = 'Credit Card';
  DateTime selectedDate = DateTime.now();
  final TextEditingController _amountController = TextEditingController();
  final TextEditingController _noteController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _amountController.dispose();
    _noteController.dispose();
    super.dispose();
  }

  void _saveExpense() async {
    final amountText = _amountController.text;
    if (amountText.isEmpty) {
      ToastUtil.showToast(context, 'Please enter an amount', isError: true);
      return;
    }
    final amount = double.tryParse(amountText);
    if (amount == null) {
      ToastUtil.showToast(
        context,
        'Please enter a valid amount',
        isError: true,
      );
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = Provider.of<AuthService>(context, listen: false).currentUser;
      if (user == null) throw Exception("User not logged in");

      final transaction = TransactionModel(
        id: '', // Generated by Firestore
        userId: user.uid,
        title: selectedCategory, // Or use a title field if added
        amount: amount,
        type: 'Expense',
        category: selectedCategory,
        date: selectedDate,
        description: "${_noteController.text} (Payment: $selectedPayment)",
      );

      await Provider.of<FirestoreService>(
        context,
        listen: false,
      ).addTransaction(transaction);

      if (mounted) {
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ToastUtil.showToast(context, 'Error saving expense: $e', isError: true);
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
        elevation: 0.5,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios_new,
            color: Theme.of(context).iconTheme.color,
            size: 20,
          ),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          'Add Expense',
          style: TextStyle(
            color: Theme.of(context).textTheme.headlineSmall?.color,
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Amount Field
            _buildLabel("Amount"),
            TextField(
              controller: _amountController,
              keyboardType: TextInputType.numberWithOptions(decimal: true),
              decoration: _inputDecoration("").copyWith(
                prefixIcon: Padding(
                  padding: const EdgeInsets.all(15),
                  child: Text(
                    Provider.of<PreferencesProvider>(context).currencySymbol,
                    style: const TextStyle(fontSize: 18, color: Colors.grey),
                  ),
                ),
                hintText: "50.00",
              ),
            ),
            const SizedBox(height: 20),

            // Category Dropdown
            _buildLabel("Category"),
            StreamBuilder<List<CategoryModel>>(
              stream: Provider.of<FirestoreService>(
                context,
                listen: false,
              ).getCategories(),
              builder: (context, snapshot) {
                final defaultCategories = [
                  'Food & Dining',
                  'Transport',
                  'Shopping',
                  'Entertainment',
                  'Health',
                  'Others',
                ];

                List<String> allCategories = [...defaultCategories];

                if (snapshot.hasData) {
                  final customCategories = snapshot.data!
                      .map((c) => c.name)
                      .toList();
                  // Avoid duplicates if user adds a category with same name
                  for (var custom in customCategories) {
                    if (!allCategories.contains(custom)) {
                      allCategories.add(custom);
                    }
                  }
                }

                // Ensure selectedCategory is in the list (validity check)
                if (!allCategories.contains(selectedCategory) &&
                    allCategories.isNotEmpty) {
                  // if current selection is invalid (e.g. was a custom category that got deleted, or init state mismatch), reset to first
                  // But strictly, we shouldn't change state during build.
                  // For dropdown value, we can fallback to display, but state needs update.
                  // For now, let's just default to first if missing.
                  if (selectedCategory.isEmpty ||
                      !allCategories.contains(selectedCategory)) {
                    selectedCategory = allCategories.first;
                  }
                }

                return _buildDropdown(
                  value: selectedCategory,
                  items: allCategories,
                  onChanged: (val) => setState(() => selectedCategory = val!),
                );
              },
            ),
            const SizedBox(height: 20),

            // Date Picker
            _buildLabel("Date"),
            InkWell(
              onTap: () async {
                final date = await showDatePicker(
                  context: context,
                  initialDate: selectedDate,
                  firstDate: DateTime(2020),
                  lastDate: DateTime(2030),
                );
                if (date != null) setState(() => selectedDate = date);
              },
              child: Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 16,
                ),
                decoration: _containerDecoration(),
                child: Row(
                  children: [
                    Icon(
                      Icons.calendar_today_outlined,
                      size: 20,
                      color: Theme.of(context).iconTheme.color,
                    ),
                    const SizedBox(width: 12),
                    Text(
                      DateFormat('MMM dd, yyyy').format(selectedDate),
                      style: TextStyle(
                        fontSize: 15,
                        color: Theme.of(context).textTheme.bodyLarge?.color,
                      ),
                    ),
                    const Spacer(),
                    const Icon(Icons.keyboard_arrow_down, color: Colors.grey),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Payment Method Dropdown
            _buildLabel("Payment Method"),
            _buildDropdown(
              icon: Icons.account_balance_wallet_outlined,
              value: selectedPayment,
              items: ['Credit Card', 'Debit Card', 'Cash', 'UPI'],
              onChanged: (val) => setState(() => selectedPayment = val!),
            ),
            const SizedBox(height: 20),

            // Notes Field
            _buildLabel("Notes"),
            TextField(
              controller: _noteController,
              maxLines: 4,
              decoration: _inputDecoration(
                "Add a brief description or note...",
              ),
            ),
            const SizedBox(height: 20),

            // Receipt Upload (Placeholder)
            _buildLabel("Receipt"),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 16),
              decoration: BoxDecoration(
                color: Theme.of(context).cardColor,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: Theme.of(context).dividerColor,
                  style: BorderStyle.solid,
                ),
              ),
              child: InkWell(
                onTap: () {
                  ToastUtil.showToast(
                    context,
                    'Receipt upload not implemented yet',
                  );
                },
                child: const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.camera_alt_outlined, color: Colors.black54),
                    SizedBox(width: 8),
                    Text(
                      "Upload Receipt Image",
                      style: TextStyle(
                        color: Colors.black54,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: Padding(
        padding: const EdgeInsets.all(20.0),
        child: SizedBox(
          width: double.infinity,
          height: 55,
          child: ElevatedButton(
            onPressed: _isLoading ? null : _saveExpense,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.mainColor,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              elevation: 0,
            ),
            child: _isLoading
                ? const CircularProgressIndicator(color: Colors.white)
                : const Text(
                    'Save Expense',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
          ),
        ),
      ),
    );
  }

  // Helper Methods
  Widget _buildLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Text(
        label,
        style: TextStyle(
          fontWeight: FontWeight.w500,
          fontSize: 14,
          color: Theme.of(context).textTheme.bodyMedium?.color,
        ),
      ),
    );
  }

  BoxDecoration _containerDecoration() {
    return BoxDecoration(
      borderRadius: BorderRadius.circular(12),
      border: Border.all(color: Theme.of(context).dividerColor),
    );
  }

  InputDecoration _inputDecoration(String hint) {
    return InputDecoration(
      hintText: hint,
      hintStyle: TextStyle(color: Theme.of(context).hintColor, fontSize: 14),
      contentPadding: const EdgeInsets.all(16),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Theme.of(context).dividerColor),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: AppColors.mainColor),
      ),
    );
  }

  Widget _buildDropdown({
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
    IconData? icon,
  }) {
    return PremiumDropdown<String>(
      value: value,
      icon: icon,
      items: items.map((String item) {
        return DropdownMenuItem<String>(value: item, child: Text(item));
      }).toList(),
      onChanged: onChanged,
    );
  }
}
